### ISSUE TITLE
Bug working with packed repositories

### ISSUE THREAD

**Issue by fdelvalle7** [AmpScm/SharpSvn#25]
Hi,

I've found a bug working with repositories that have been packed with the command "svnadmin pack".

When some method like "Log" or "Export" needs to read revprops from packed revisions an exception like this is thrown:
SvnErrorCode: SVN_ERR_MALFORMED_FILE
Message: "Failed to parse revprops for r860"
InnerException: "Serialized hash missing terminator"

To reproduce the error, Follow this steps:

1) Create a test repository with more than 1000 revisions. In my case, I've generated a repository with 1050 revisions of a single file (doc.txt)
2) Use the method "Log" to retrieve all the revisions of the repository or a single file. It will work.
3) Pack the repository using "svnadmin pack". 
4) Use the method "Log" to retrieve all the revisions of the repository or a single file. It will throw a exception. Maybe it's a parallelism problem, because each time I execute the test the revision that causes the exception changes. Note that the revision that causes the exception always go from 1 to 1000 (1001 to 1050 are not packed).

This fails with the last version (1.14001.54.0) but works with an old one (1.9005.3957.231) 

I've attached the test repository both pack and unpacked
[svn-test-packed.zip](https://github.com/AmpScm/SharpSvn/files/7470070/svn-test-packed.zip)
[svn-test-unpacked.zip](https://github.com/AmpScm/SharpSvn/files/7470071/svn-test-unpacked.zip)

**Comment by rhuijben** [comment]
Can you reproduce this with the normal Subversion binaries?
(The SlikSvn binaries from https://sliksvn.com/en/download use almost an identical build as SharpSvn)
In that case you should report this issue at the Subversion project.

We don't implement this level of support directly in SharpSvn... We just link the standard libraries inside and this will most likely cause the issue. Otherwise it would be some compatibility tweak in our build scripts.

**Comment by fdelvalle7** [comment]
SlikSvn works, I have no problems reading the log of the repository. I can read it with TortoiseSvn too.

I've tested it with latest version of SlikSVN x64: svn, version 1.14.1-SlikSvn (SlikSvn/1.14.1)

**Comment by rhuijben** [comment]
This appears to be a very deep bug inside Subversion itself related to the fsfs in-memory caching, which we by default disable in SharpSvn (for concurrency reasons). I now enabled a small cache for the next version.

$ `svn log --xml -v --with-all-revprops --config-option config:miscellany:memory-cache-size=0 file:///F:/path-to-repos` should be able to reproduce these issues, but I had a hard time doing that.

**Comment by fdelvalle7** [comment]
Tested and working. Thanks.
