### ISSUE TITLE
Upgrade OpenSSL to 3.0

### ISSUE THREAD

**Issue by pde-cds** [AmpScm/SharpSvn#39]
The OpenSSL Team announced the end of support of OpenSSL at 11th September 2023 and recomments to upgrade OpenSSL to 3.0 before this date.

This is the original announcement:

OpenSSL 3.0 has recently been designated as a Long Term Support (LTS) release. This means that it will now be supported until 7th September
2026 (5 years after its initial release).

Our previous LTS release (1.1.1) will continue to be supported until 11th September 2023.

We encourage all users to upgrade to 3.0.

Yours,
The OpenSSL Project Team

**Comment by rhuijben** [comment]
We will upgrade as soon as Apache Subversion and Apache Serf support building against OpenSSL 3.0.

**Comment by shbeck** [comment]
I [asked](https://lists.apache.org/thread/905pdq5gzvsdqxw8xhvt5jnhjhhr79ns) at users@apache.org on OpenSSL 3.x support and this is what I got:

Effectively there's a yet unreleased patch for Apache Serf (https://build.opensuse.org/package/view_file/devel:libraries:c_c++/libserf/openssl3.patch, resp. [r1901937](https://lists.apache.org/thread/krw575hhg3xc9dnw3qj4o85ycj449tvv)) that allows to build against OpenSSL 3.0.

So I guess that either that patch needs to be applied in SharpsSvn's build or we wait for the next Serf release with that patch.

**Comment by shbeck** [comment]
Apache Serf has released OpenSSL 3 support with version 1.3.10, see https://svn.apache.org/repos/asf/serf/branches/1.3.x/CHANGES. Apache Subversion has at least updated its trunk already, see https://svn.apache.org/repos/asf/subversion/trunk/?r=1910152, however the next version 1.15 still seems to take a while, as they don't even have a branch for it yet.

**Comment by pde-cds** [comment]
Created a PullRequest with an integrated OpenSSL 3.0.12 https://github.com/AmpScm/SharpSvn/pull/89. 
Any thoughts about this?

**Comment by shbeck** [comment]
PullRequest with OpenSSL 3.0.12 has been merge - issue fixed (https://github.com/AmpScm/SharpSvn/pull/89).
