### ISSUE TITLE
Repository file changes

### ISSUE THREAD

**Issue by 563256676** [AmpScm/SharpSvn#49]
I want to get a list of file changes through SharpSvn, is there any way I can monitor file changes in the repository? For example add, delete, rename, conflict.

**Comment by rhuijben** [comment]
Subversion -unlike git- has a clear distinction between a repository and a working copy. Conflicts can only happen on the client side, as server sides conflicts are a commit error.

You can see clientside status using SvnClient.Status() / .GetStatus().

Server side you can analyze the history/changes using .Log()/.GetLog().

See some examples for this in the C# test projects in this repository, and there are quite a few examples on the StackOverflow site.

As this request is not an issue, I'll close this issue in the issuetracker.
