### ISSUE TITLE
TortoiseSVN 1.9 repository is not compatible

### ISSUE THREAD

**Issue by 563256676** [AmpScm/SharpSvn#50]
TortoiseSVN version 1.9 is installed on my computer. When I use SharpSVN version 1.14001.156, I can create a repository, but an exception occurs when Committing.

Expected FS format between '1' and '7'; found format '8'

This problem does not occur when I use TortoiseSVN 1.10 version, what is the compatibility range of SharpSVN 1.14001.156? Is it backward compatible?

**Comment by rhuijben** [comment]
Subversion 1.10 introduced repository changes, but SharpSvn was not updated for the repository version yet, so creating an 1.9 compatible version with 1.10+ will make it 1.10+. Workaround is creating an 1.8 version. The fix will be in the next version, as it was merged to main for issue #49. It also has a fix to make sure this doesn't happen again in future versions.

I would recommend separating your repository and Subversion server, for all the good reasons documented in the Subversion book and faq though

**Comment by rhuijben** [comment]
A snapshot, with the fix is available. See issue #49.
